import RolePermission from "../models/rolePermission.model.js";

export const defaultMatrix = {
    admin: {
        readProduct: true,
        createProduct: true,
        updateProduct: true,
        deleteProduct: true,
        readOrder: true,
        createOrder: true,
        updateOrder: true,
        deleteOrder: true,
        readCustomer: true,
        createCustomer: true,
        updateCustomer: true,
        deleteCustomer: true,
        readInventory: true,
        createInventory: true,
        updateInventory: true,
        deleteInventory: true,
        readDiscount: true,
        createDiscount: true,
        updateDiscount: true,
        deleteDiscount: true,
        readSupplier: true,
        createSupplier: true,
        updateSupplier: true,
        deleteSupplier: true,
        readPurchaseOrder: true,
        createPurchaseOrder: true,
        updatePurchaseOrder: true,
        deletePurchaseOrder: true,
        readInvoice: true,
        readReport: true,
        createReturn: true,
        readReturn: true,
        readPayment: true,
        readUser: true,
        createUser: true,
        updateUser: true,
        deleteUser: true,
    },
    manager: {
        readProduct: true,
        createProduct: true,
        updateProduct: true,
        deleteProduct: true,
        readOrder: true,
        createOrder: true,
        updateOrder: true,
        deleteOrder: true,
        readCustomer: true,
        createCustomer: true,
        updateCustomer: true,
        deleteCustomer: true,
        readInventory: true,
        createInventory: true,
        updateInventory: true,
        deleteInventory: true,
        readDiscount: true,
        createDiscount: true,
        updateDiscount: true,
        deleteDiscount: true,
        readSupplier: true,
        createSupplier: true,
        updateSupplier: true,
        deleteSupplier: true,
        readPurchaseOrder: true,
        createPurchaseOrder: true,
        updatePurchaseOrder: true,
        deletePurchaseOrder: true,
        readInvoice: true,
        readReport: true,
        createReturn: true,
        readReturn: true,
        readPayment: true,
        readUser: true,
        createUser: true,
        updateUser: true,
        deleteUser: false,
    },
    cashier: {
        readProduct: true,
        createProduct: false,
        updateProduct: false,
        deleteProduct: false,
        readOrder: true,
        createOrder: true,
        updateOrder: true,
        deleteOrder: false,
        readCustomer: true,
        createCustomer: true,
        updateCustomer: true,
        deleteCustomer: false,
        readInventory: true,
        createInventory: false,
        updateInventory: false,
        deleteInventory: false,
        readDiscount: true,
        createDiscount: false,
        updateDiscount: false,
        deleteDiscount: false,
        readSupplier: false,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        readPurchaseOrder: false,
        createPurchaseOrder: false,
        updatePurchaseOrder: false,
        deletePurchaseOrder: false,
        readInvoice: true,
        readReport: false,
        createReturn: true,
        readReturn: true,
        readPayment: true,
        readUser: false,
        createUser: false,
        updateUser: false,
        deleteUser: false,
    },
    staff: {
        readProduct: true,
        createProduct: false,
        updateProduct: false,
        deleteProduct: false,
        readOrder: true,
        createOrder: false,
        updateOrder: true,
        deleteOrder: false,
        readCustomer: true,
        createCustomer: false,
        updateCustomer: false,
        deleteCustomer: false,
        readInventory: true,
        createInventory: false,
        updateInventory: true,
        deleteInventory: false,
        readDiscount: false,
        createDiscount: false,
        updateDiscount: false,
        deleteDiscount: false,
        readSupplier: true,
        createSupplier: false,
        updateSupplier: false,
        deleteSupplier: false,
        readPurchaseOrder: true,
        createPurchaseOrder: false,
        updatePurchaseOrder: true,
        deletePurchaseOrder: false,
        readInvoice: true,
        readReport: false,
        createReturn: false,
        readReturn: true,
        readPayment: false,
        readUser: false,
        createUser: false,
        updateUser: false,
        deleteUser: false,
    },
};

export async function ensureRolePermissions() {
    const roles = Object.keys(defaultMatrix);
    for (const role of roles) {
        const existing = await RolePermission.findOne({ role });
        if (!existing) {
            await RolePermission.create({
                role,
                permissions: defaultMatrix[role],
            });
        }
    }
}
